### ISSUE TITLE
Language forced to first entry in configuration array

### ISSUE THREAD

**Issue by mrfatguy** [lajax/yii2-language-picker#11]
An example Yii2 configuration:

```
'language' => 'pl',
'sourceLanguage' => 'en',
```

And an example yii2-language-picker configuration:

```
'languagepicker' => [
    'class' => 'lajax\languagepicker\Component',
    'languages' => [
        'en' => 'English',
        'pl' => 'polski'
    ]
]
```

When application is first time run, it starts in _English_ language, while is should in _polski_, because current language is set to `pl` in application configuration. It seems, that yii2-language-picker is changing application language to first item in `languages` array in its own configuration, ignoring current application configuration.

**Comment by lajax** [comment]
Thanks for your comment.

This occurs because the extension tries to guess the user's language based on the browser's language settings. In this case it is likely that English is being used by the browser.

**Comment by mrfatguy** [comment]
That sounds great. But, I think you may want to consider parametrizing this, so "guessing" would be controlled by developer, who uses your (great anyway) extension. Currently it is a bit confusing, so at your place, I'd consider some kind of flag, if language should be read from Yii2 or "guessed".

No matter, if you implement this feature (parametrization) or not, you can close this issue, as it turns out, that it is not a bug at all.
