### ISSUE TITLE
Language picker into navbar

### ISSUE THREAD

**Issue by FedericoBenedetti1976** [lajax/yii2-language-picker#15]
Hi, great job. I'm asking if there's a way to include the language-picker into the navbar.

Thank's

**Comment by moltam** [comment]
You can insert the widget inside the navbar, if you wrap the widget into an element with "navbar-text".

Example:

``` php
<div class="navbar-text pull-right">
    <?= 
        \lajax\languagepicker\widgets\LanguagePicker::widget([
            'skin' => \lajax\languagepicker\widgets\LanguagePicker::SKIN_DROPDOWN,
            'size' => \lajax\languagepicker\widgets\LanguagePicker::SIZE_LARGE
        ]);
    ?>
</div>
```

![lp](https://cloud.githubusercontent.com/assets/4578365/7783707/7b830cbc-014b-11e5-9166-6d33b75d9d66.jpg)

I hope this is what you meant.

**Comment by lajax** [comment]
Thanks!
