### ISSUE TITLE
not changing language

### ISSUE THREAD

**Issue by ajithfort** [lajax/yii2-language-picker#16]
its not working for me.  this my config file

```
'language' => 'en',
'bootstrap' => ['languagepicker'],
    'controllerNamespace' => 'frontend\controllers',
    'defaultRoute'        => 'site/home',
    'components'          => [

    'languagepicker' => [
    'class' => 'lajax\languagepicker\Component',
    'languages' => ['en' => 'English', 'de' => 'Deutsch', 'fr' => 'Français'] , 
    ],

   'urlManager' => [

        'class' => 'yii\web\UrlManager',
        'enablePrettyUrl' => true,
        'showScriptName' => false,
         'rules' => array(
            '<controller:\w+>/<id:\d+>' => '<controller>/view',
            '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
            '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
    ),
    ],
```

and in view file i added this 

<?= \lajax\languagepicker\widgets\LanguagePicker::widget([
    'skin' => \lajax\languagepicker\widgets\LanguagePicker::SKIN_DROPDOWN,
    'size' => \lajax\languagepicker\widgets\LanguagePicker::SIZE_LARGE
]); ?>

then a selector appeared (flag with country name) when i select german flag or french i expect my
website to change to that language, but its still English.
![screenshot from 2015-07-31 11 10 48](https://cloud.githubusercontent.com/assets/11402503/9001460/6bb7c510-3775-11e5-9c58-9e138e13da1f.png)
![screenshot from 2015-07-31 11 10 56](https://cloud.githubusercontent.com/assets/11402503/9001462/71390684-3775-11e5-91b1-0076d4a5188a.png)

**Comment by lajax** [comment]
Doesn't the javascript throw an error?

**Comment by georgejr** [comment]
I had the same problem, when I realised, that I did not changed the cookie domain:)
