### ISSUE TITLE
Can we use yii2-language-picker and yii2-translate-manager simultaneously.

### ISSUE THREAD

**Issue by rahulk-k** [lajax/yii2-language-picker#19]
Hi,
Is it possible to use yii2-language-picker and yii2-translate-manager simultaneously.
If yes than how can i configure bootstrap property.

**Comment by moltam** [comment]
Hi, you can use them simultaneously. 

You can pass the available languages to the language-picker via a callback (modify the return value, if you need a different array format):

``` php
'languagepicker' => [
    // ....
    'languages' => function () {
        return \lajax\translatemanager\models\Language::getLanguageNames(true);
    },
    // ....
],
```

As for the bootstrap part, I think the order doesn't matter. But I didn't test it deeply.

**Comment by StalkAlex** [comment]
This function is deprecated now. What should I use instead?
