### ISSUE TITLE
Flag for Odia language,India

### ISSUE THREAD

**Issue by seshadri-baral** [lajax/yii2-language-picker#27]
I cant get the correct flag for the language Odia( language code - or/ori),which is an Indian language. besides I get the correct flag for Hindi. How can I change the flag in such situation?
![languages_flags](https://cloud.githubusercontent.com/assets/975779/21109173/e6022586-c0bd-11e6-9b20-cf28c6b4db18.jpg)

**Comment by moltam** [comment]
You can override the default assets packed with the extension.

See config section in the readme:

```php
<?= \lajax\languagepicker\widgets\LanguagePicker::widget([
    'languageAsset' => 'lajax\languagepicker\bundles\LanguageLargeIconsAsset',      // StyleSheets
]); ?>
```

You just need to create you own [stylesheet](https://github.com/lajax/yii2-language-picker/blob/master/assets/stylesheets/flags.css), and [assetbundle](https://github.com/lajax/yii2-language-picker/blob/master/bundles/LanguageLargeIconsAsset.php), wich contains the flags you need.
