### ISSUE TITLE
Picker fails to change language

### ISSUE THREAD

**Issue by mrfatguy** [lajax/yii2-language-picker#9]
Nope, not only #8 is the problem. Either I'm doing something really wrong or there is some bug in your extension. I followed home page instruction step-by-step, but I'm getting strange results.

My `components` configuration:

```
'languagepicker' => [
    'class' => 'lajax\languagepicker\Component',
    'languages' => ['en' => 'English', 'pl' => 'polski', 'fr' => 'Français']
]
```

and code added to view (layout):

```
<?= \lajax\languagepicker\widgets\LanguagePicker::widget([
    'skin' => \lajax\languagepicker\widgets\LanguagePicker::SKIN_DROPDOWN,
    'size' => \lajax\languagepicker\widgets\LanguagePicker::SIZE_LARGE
]); ?>
```

Widget renders itself correctly and when clicked (with `suffix` disabled -- see #8 -- because with `suffix` enabled, it does not work at all) it reload page, but language remains unchanged.

What surprised me the most (actually, shocked a bit), was that your widget claims, that language has actually been changed (displaying _destination_ language name and flag), while rest of the page remains in unchanged _previous_ language). See picture below:

![lang-1](https://cloud.githubusercontent.com/assets/2903392/6937328/23587f54-d85b-11e4-9eaa-d93c068d1e4e.png)

This suggests, that it does not use `Yii::$app->language` to check the current language, which is pretty weird. What, then, you're using to check the language and draw proper flag?

**Comment by lajax** [comment]
Did you add the languagepicker extension to the bootsrap array in the config?

``` php
'language' => 'en',
'bootstrap' => ['languagepicker'],
'components' => [
    'languagepicker' => [
        'class' => 'lajax\languagepicker\Component',
        'languages' => ['en', 'de', 'fr']                   // List of available languages (icons only)
    ]
],
```

**Comment by mrfatguy** [comment]
My inital report of this bug was made a week ago. After reporting it, I have removed your extension. Now, I have reinstalled it and everything now works fine. However, I don't know, if this is because, you introduced some fixes in commits made few days ago, or if you're right -- that I forgot to put `'bootstrap' => ['languagepicker']`. Anyway, this particular issue is resolved and you may close it, if you wish. Thank you.
